name: Update Spotify Top50 Playlist

on:
  schedule:
    # JST 月曜 00:00 に実行したい → UTC で指定する必要あり（下で計算を説明）
    - cron: '0 15 * * 0'   # == UTC Sunday 15:00 → JST Monday 00:00
  workflow_dispatch:      # 手動トリガー（テスト用）

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run top50 script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REFRESH_TOKEN: ${{ secrets.SPOTIPY_REFRESH_TOKEN }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        run: |
          python top50_4weeks.py
          python top50_6months.py
          python top50_entire.py
